export const lightTheme = {
  dark: false,
  colors: {
    primary: "#FDE616",
    background: "white",
    card: "green",
    text: "black",
    border: "black",
    notification: "green",
    accent: "darkBlue",
    labelText: "grey",
    disabled: "grey",
    validator: "red",
    containerColor: "lightgreen",
    iconColor: "white",
    buttonColor: "#FDE616",
    googleButtonColor: "#00000009",
    buttonTextColor: "black",
  },
};

export const darkTheme = {
  dark: true,
  colors: {
    primary: "#FDE616",
    background: "black",
    card: "green",
    text: "white",
    border: "white",
    notification: "red",
    accent: "red",
    labelText: "lightgrey",
    disabled: "grey",
    validator: "red",
    containerColor: "red",
    iconColor: "black",
    buttonColor: "#FDE616",
    googleButtonColor: "#FFFFFF15",
    buttonTextColor: "black",
  },
};
